### Numpy
Numpy is a powerful library in Python used for numerical computations. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures.

- [YouTube Video: Numpy Tutorial](https://www.youtube.com/watch?v=x7ULDYs4X84)  
- [W3Schools: Numpy](https://www.w3schools.com/python/numpy)

#### Summary

This script demonstrates key features of the NumPy library for numerical computations in Python:

- **Array Creation:** Shows how to create arrays of various dimensions (scalars, vectors, matrices, and 3D arrays) using `np.array` and `np.zeros`.
- **Array Properties:** Uses `.ndim` to display the number of dimensions of arrays.
- **Sorting:** Demonstrates sorting arrays with `np.sort`.
- **Concatenation:** Shows how to concatenate arrays with `np.concatenate`.
- **Indexing and Slicing:** Explains and demonstrates array indexing and slicing, including advanced slicing with steps and negative indices.
- **Accessing Elements:** Shows how to access specific elements in 1D, 2D, and 3D arrays.
- **Variable Overview:** Lists and describes the main variables created in the script, including their types and shapes.

Useful resources:
- [YouTube Video: Numpy Tutorial](https://www.youtube.com/watch?v=x7ULDYs4X84)
- [W3Schools: Numpy](https://www.w3schools.com/python/numpy)


In [167]:
import numpy as np


In [168]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [169]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

In [171]:
arr_sorted = np.sort([
    [4,5,6],
    [7,8,9],
    [1,2,3],
])
arr_sorted

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [172]:
np.concatenate([
    [1,2,3],
    [4,5,6,7],
])

array([1, 2, 3, 4, 5, 6, 7])

In [173]:
arr = np.array([1,2,3,4,5])

print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [174]:
np.__version__

'2.2.6'

In [175]:
np.array(100)

array(100)

In [176]:
from pprint import pprint

d0 = np.array(30)
d1 = np.array([1, 2, 3])
d2 = np.array([[1, 2, 3], [4, 5, 6]])
d3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("d0:")
pprint((d0, d0.ndim))
print("\nd1:")
pprint((d1, d1.ndim))
print("\nd2:")
pprint((d2, d2.ndim))
print("\nd3:")
pprint((d3, d3.ndim))


d0:
(array(30), 0)

d1:
(array([1, 2, 3]), 1)

d2:
(array([[1, 2, 3],
       [4, 5, 6]]), 2)

d3:
(array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]]), 3)


In [177]:
# define the number of dimensions
np.array([[1],[2]], ndmin=3)

array([[[1],
        [2]]])

In [178]:
arr = np.array([11, 22, 33, 44, 55, 66])

arr2 = np.array([
    [1, 2, 3, 4, 5, 6],                 # i-0
    [11, 22, 33, 44, 55, 66],           # i-1
])

print('Array:', arr)
print('Index[2]:', arr[2])


print('[1nd Row, 4 Element]: ', arr2[0, 3])
print('[2nd Row, 1 Element]: ', arr2[1, 0])

Array: [11 22 33 44 55 66]
Index[2]: 33
[1nd Row, 4 Element]:  4
[2nd Row, 1 Element]:  11


In [179]:
# Create a 3-dimensional numpy array called arr3.
# It contains two 2x3 sub-arrays.
arr3 = np.array([
    [[1, 2, 3], [4, 5, 6]],       # First 2x3 sub-array
    [[7, 8, 9], [10, 11, 22222]],   # Second 2x3 sub-array with a notable value 22222
])

# Print specific elements from arr3 with descriptive comments.
# arr3[1, 0, 2] access: Element in 2nd sub-array, 1st row, 3rd column.
print('1st row, 3rd column: of Third element', arr3[1, 0, 2])

# arr3[1, 1, 1] access: Element in 2nd sub-array, 2nd row, 2nd column.
print('2nd row, 2nd column: of Second element ', arr3[1, 1, 1])

# arr3[1, 1, 2] access: Element in 2nd sub-array, 2nd row, 3rd column.
print('2nd row, 3rd column: of Third element', arr3[1, 1, 2])


1st row, 3rd column: of Third element 9
2nd row, 2nd column: of Second element  11
2nd row, 3rd column: of Third element 22222


### Existing Variables

| Variable   | Type          | Value Description                                   |
|------------|---------------|-----------------------------------------------------|
| arr        | numpy.ndarray | [11, 22, 33, 44, 55, 66]                             |
| arr2       | numpy.ndarray | 2×6 array: [[ 1,  2,  3,  4,  5,  6], [11, 22, 33, 44, 55, 66]] |
| arr3       | numpy.ndarray | 3D array with shape (2, 2, 3)                       |
| arr_sorted | numpy.ndarray | 3×3 array: [[4, 5, 6], [7, 8, 9], [1, 2, 3]]         |
| d0         | numpy.ndarray | 30                                                |
| d1         | numpy.ndarray | [1, 2, 3]                                         |
| d2         | numpy.ndarray | 2×3 array: [[1, 2, 3], [4, 5, 6]]                   |
| d3         | numpy.ndarray | 3D array with shape (2, 2, 2)                       |

### Slicing Arrays

Slicing in Python means taking elements from one given index to another.

#### Syntax

- Basic slice: `[start:end]`
- Slice with step: `[start:end:step]`

#### Default Values

- **start**: If not provided, defaults to `0`.
- **end**: If not provided, defaults to the length of the array in that dimension.
- **step**: If not provided, defaults to `1`.

> Note: The result includes the start index, but excludes the end index.

In [180]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

#  from index 2 (inclusive) to 6 (exclusive)
print('[2:6] --->', arr[2:6])
#  from index 3 to the end
print('[3:] --->', arr[3:])
# beginning up to (but not including) index 4
print('[:4] --->', arr[:4])
# Slicing every second element starting from index 1
print('[1::2] --->', arr[1::2])
# Slicing to get the second last element (slice from -2 to -1)
print('[-2:-1] --->', arr[-2:-1])
# Slicing to reverse the array: last element to the 5th last element (not inclusive)
print('[-1:-5:-1] --->', arr[-1:-5:-1])

[2:6] ---> [3 4 5 6]
[3:] ---> [4 5 6 7]
[:4] ---> [1 2 3 4]
[1::2] ---> [2 4 6]
[-2:-1] ---> [6]
[-1:-5:-1] ---> [7 6 5 4]


In [181]:
arr = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10]
])

print('[1, 0:3] --->',arr[1, 0:3])
print('[0:1, 3] --->', arr[0:1, 3])
print('[0:1, 1:3] --->', arr[0:1, 2:4])

[1, 0:3] ---> [6 7 8]
[0:1, 3] ---> [4]
[0:1, 1:3] ---> [[3 4]]
