### Numpy Data Types

- [W3Schools: Numpy Data Types](https://www.w3schools.com/python/numpy/numpy_data_types.asp)
- [Numpy Structured Data](https://jakevdp.github.io/PythonDataScienceHandbook/02.09-structured-data-numpy.html)

In [1]:
import numpy as np

### NumPy Data Types

NumPy arrays are homogeneous in type, meaning each element in an array uses the same data type (dtype). This allows for efficient storage and computation.

#### Common Data Types

- **Integer Types:**
    - `np.int8`, `np.int16`, `np.int32`, `np.int64`: Signed integers of different byte sizes.
    - `np.uint8`, `np.uint16`, `np.uint32`, `np.uint64`: Unsigned integers.

- **Floating Point Types:**
    - `np.float16`, `np.float32`, `np.float64`: Floating point numbers with different precision levels.

- **Boolean Type:**
    - `np.bool_`: Representing `True`/`False`.

- **Complex Types:**
    - `np.complex64`, `np.complex128`: Complex numbers with various precisions.

- **Other Types:**
    - `np.object_`: Generic Python objects.
    - `np.str_` or `np.unicode_`: String data.
    - `np.datetime64` and `np.timedelta64`: Time-based data.

#### How to Check and Convert Data Types

- **Check dtype:**  
    You can view the dtype of a NumPy array using the `.dtype` attribute.  
    Example:  
    ```python
    print(arr.dtype)
    ```

- **Convert dtype:**  
    Use the `.astype()` method to cast an array to a new type.  
    Example:  
    ```python
    arr_float = arr.astype(np.float64)
    ```

#### Notes

- When you create an array, you can specify the data type explicitly using the `dtype` parameter in functions like `np.array()`.
- If no `dtype` is specified, NumPy will infer the type from the provided data.
- Consistent data types across arrays enable efficient vectorized operations, a key strength of NumPy.

This documentation covers the basics of NumPy data types and how they benefit efficient numerical computations.

In [2]:
arr_int = np.array([1,2,3])
arr_str = np.array(['a', 'bb', 'ccc'])

print("[1,2,3] ---> ", arr_int.dtype)
print("['a', 'bb', 'ccc'] ---> ", arr_str.dtype)

[1,2,3] --->  int64
['a', 'bb', 'ccc'] --->  <U3


In NumPy, dtypes (data types) specify how the data in the array is stored. The dtype `"U3"` is a Unicode string type where:

- **U** stands for Unicode.
- **3** indicates that each element can hold up to 3 Unicode characters.

Confirming that each string element is a Unicode string of length 3.

In [3]:
arr_int_1 = np.array([1, 2, 3], dtype='i1')
arr_int_16 = np.array([1, 2, 3], dtype='i2')
arr_int_32 = np.array([1, 2, 3], dtype='i4')

print("[dtype='i1'] ---> ", arr_int_1.dtype)
print("[dtype='i2'] ---> ", arr_int_16.dtype)
print("[dtype='i4'] ---> ", arr_int_32.dtype)

[dtype='i1'] --->  int8
[dtype='i2'] --->  int16
[dtype='i4'] --->  int32


### Handling Value Errors in NumPy  

NumPy raises a **`ValueError`** when data cannot be safely cast to the specified type, such as converting invalid strings to numbers or exceeding fixed string lengths.  

#### Example: Failed Type Conversion  
```python  
import numpy as np  
try:  
    # Fails because 'a' is not a valid integer  
    arr = np.array(['a', '2', '3'], dtype='i')  
except ValueError as e:  
    print(f"ValueError: {e}")  # Output: ValueError: invalid literal for int() with base 10: 'a'  
```  

#### Common NumPy Exceptions  
- **`ValueError`** – Occurs when an operation receives a valid type but an **invalid value** 
    - (e.g., wrong shape, unconvertible data).  
- **`TypeError`** – Triggered when an operation is performed on an **unsupported data type** 
    - (e.g., adding a string to a float).  

`ValueError` helps catch issues where the input is syntactically correct but logically unsuitable.


In [4]:
import numpy as np
# Example of ValueError in NumPy
try:
    arr = np.array(['a', '2', '3'], dtype='i') # ValueError, as 'a' cannot be converted to an integer
except ValueError as e:
    print(f"ValueError: {e}")

ValueError: invalid literal for int() with base 10: 'a'


In [5]:
import numpy as np
arr = np.array([1, 2, 3])
try:
    result = arr + 'string'  # This will raise a TypeError
except TypeError as e:
    print(f"TypeError: {e}")

TypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U6')) -> None


#### Converting Data Type on Existing Arrays

One of the simplest ways to change a NumPy array's data type is to use the `astype()` method, which returns a new array with the specified type. For example:

```python
arr_float = arr.astype('float')
arr_int = arr.astype(int)
```

#### Example of Changing Data Type

```python
import numpy as np
# Create an array of strings
arr = np.array(['1.5', '2.5', '3.5'])
# Convert to float
arr_float = arr.astype(np.float64)
# Convert to integer (will truncate the decimal part)
arr_int = arr_float.astype(np.int64)
print(arr_float)  # Output: [1.5 2.5 3.5]
print(arr_int)    # Output: [1 2 3]
```
#### Summary
NumPy's data types are crucial for efficient numerical computations, allowing for optimized storage and operations. Understanding how to check and convert data types is essential for effective data manipulation in NumPy. The `astype()` method is a powerful tool for changing the data type of existing arrays, enabling flexibility in handling various data formats. Always be cautious of potential `ValueError` exceptions when converting incompatible data types.

In [6]:
# This does not equal 0 due to floating-point precision
0.3 - 0.2 - 0.1

-2.7755575615628914e-17

In [7]:
import numpy as np

print(np.array([1, 3, 5.5, 7.7, 9.2], dtype=np.uint8))
print(np.array([1. , 3. , 5.5, 7.7, 9.2], dtype='float32'))

# np.single to whatever fixed-size type your platform supports
print(np.array([1, 3, 5.5, 7.7, 9.2], dtype=np.single))

[1 3 5 7 9]
[1.  3.  5.5 7.7 9.2]
[1.  3.  5.5 7.7 9.2]


In [8]:
names = np.array(["bob", "amy", "han"], dtype=str)
# array(['bob', 'amy', 'han'], dtype='<U3') # <U3 means Unicode string of max length 3
print("names.itemsize: ", names.itemsize)

more_names = np.array(["bobo", "jehosephat"]) # 4+10=14
# array(['bobo', 'jehosephat'], dtype='<U10')
print("more_names.itemsize: ", more_names.itemsize)

np.concatenate((names, more_names))
# array(['bob', 'amy', 'han', 'bobo', 'jehosephat'], dtype='<U10')

names.itemsize:  12
more_names.itemsize:  40


array(['bob', 'amy', 'han', 'bobo', 'jehosephat'], dtype='<U10')

#### Converting Data Type

In [9]:
arr_float = np.array([-1, 1, 0, 1.11, 3.1])
arr_int32 = arr_float.astype('i') # 'i' defaults to int32
arr_int64 = arr_float.astype(int) # int defaults to int64
arr_bool = arr_float.astype(bool) # converts to boolean

print('Arr:', arr_float)
print('==========================')
print("arr_float.astype('i'): ", arr_float.dtype)
print("arr_int32.astype('int'): ", arr_int32.dtype)
print("arr_int64.astype('int'): ", arr_int64.dtype)
print("arr_bool.astype('bool'): ", arr_bool.dtype)

arr_int32, arr_int64, arr_bool

Arr: [-1.    1.    0.    1.11  3.1 ]
arr_float.astype('i'):  float64
arr_int32.astype('int'):  int32
arr_int64.astype('int'):  int64
arr_bool.astype('bool'):  bool


(array([-1,  1,  0,  1,  3], dtype=int32),
 array([-1,  1,  0,  1,  3]),
 array([ True,  True, False,  True,  True]))

### Structured Arrays 
Structured arrays allow you to create arrays with complex data types, where each element can have multiple fields of different types. 
This is useful for representing structured data like records or tables.

### Summary of NumPy Data Types
- **Homogeneous**: All elements in a NumPy array have the same data type.
- **Efficient**: Using specific data types allows for optimized memory usage and performance.
- **Flexible**: You can convert between data types using the `astype()` method.
- **Structured Arrays**: Enable complex data types with multiple fields.

#### Numpy String Types

Assuming you want to define a `numpy.dtype` for the `employee.name` field where the name has no fixed length (i.e., it could be of any length), 

- **Fixed-length string:** `S<N>` or `U<N>` (e.g., `S20` for bytes, `U20` for unicode)
- **Object type:** `object` (can hold arbitrary objects, including Python `str` of any length)

In [12]:
import numpy as np
# Define a structured data type with fields 'name' and 'age'
dtype = np.dtype([('name', 'U10'), ('age', 'i4')])

# Create a structured array with the defined dtype
arr = np.array([('Alice', 30), ('Bob', 25)], dtype=dtype)

# Accessing fields in the structured array
print(arr['name'])  # Output: ['Alice' 'Bob']
print(arr['age'])   # Output: [30 25]

['Alice' 'Bob']
[30 25]


##### Comprehensive structured array example with multiple fields

In [14]:
# Define a complex data type for employee records including age
employee_dtype = np.dtype([
    ('employee_id', np.int64), # 8-byte (i.e., 64 bit) float.
    ('name', np.object_), # np.object_ == object
    ('age', np.int32), # 'i4' translates to 4-byte (i.e., 32 bit) integer,
    ('department', 'U15'), # Unicode string of maximum length 15
    ('salary', 'f8'),
    ('hire_date', 'datetime64[D]'),
    ('is_active', 'bool'),  # 'bool' == np.bool_
])

# using dictionary syntax
np.dtype({
    'names': ('employee_id', 'name', 'age', 'department', 'salary', 'hire_date', 'is_active'),
    'formats': ('i8', 'O', 'i4', 'U15', 'f8', 'M8[D]', '?')
})

# Create employee data with ages
employees = np.array([
    (101, 'Heer Smith', 35, 'Compuer Science', 75000.50, '2022-01-15', True),
    (102, 'Dipenparmar12', 35, 'Compuer Science', 68000.00, '2021-03-10', True),
    (103, 'Arjun Wilson', 29, 'Sales', 72000.75, '2020-11-05', False),
    (104, 'Diviya Davis', 40, 'Engineering', 82000.00, '2023-02-20', True),
    (105, 'Prakash Brown', 50, 'HR', 65000.25, '2019-08-12', True)
], dtype=employee_dtype)

print("Employee Records:")

print("=" * 50)
print(f"Total employees: {len(employees)}")
print(f"Active employees: {np.sum(employees['is_active'])}")
print(f"Average salary: ${np.mean(employees['salary']):.2f}")

print("\nDepartment breakdown:")
print(f"Engineering: {np.sum(employees['department'] == 'Engineering')}")
print(f"Compuer Science: {np.sum(employees['department'] == 'Compuer Science')}")
print(f"Sales: {np.sum(employees['department'] == 'Sales')}")
print(f"HR: {np.sum(employees['department'] == 'HR')}")

# Demonstrate field access and filtering
print("\nActive Engineering employees:")
eng_active = employees[(employees['department'] == 'Engineering') & (employees['is_active'])]
eng_active
# for emp in eng_active:
#     print(f"ID: {emp['employee_id']}, Name: {emp['name']}, Salary: ${emp['salary']}")

Employee Records:
Total employees: 5
Active employees: 4
Average salary: $72400.30

Department breakdown:
Engineering: 1
Compuer Science: 2
Sales: 1
HR: 1

Active Engineering employees:


array([(104, 'Diviya Davis', 40, 'Engineering', 82000., '2023-02-20',  True)],
      dtype=[('employee_id', '<i8'), ('name', 'O'), ('age', '<i4'), ('department', '<U15'), ('salary', '<f8'), ('hire_date', '<M8[D]'), ('is_active', '?')])

### NumPy Data Type Character Codes

| Character | Description | Example |
|-----------|-------------|---------|
| 'b' | Byte | `np.dtype('b')` |
| 'i' | Signed integer | `np.dtype('i4') == np.int32` |
| 'u' | Unsigned integer | `np.dtype('u1') == np.uint8` |
| 'f' | Floating point | `np.dtype('f8') == np.float64` |
| 'c' | Complex floating point | `np.dtype('c16') == np.complex128` |
| 'S', 'a' | String | `np.dtype('S5')` |
| 'U' | Unicode string | `np.dtype('U') == np.str_` |
| 'V' | Raw data (void) | `np.dtype('V') == np.void` |

These character codes provide a shorthand way to specify data types when creating NumPy arrays or defining structured array fields.