### NumPy Array Reshaping

`Reshaping` is the process of changing the shape (dimensions) of a NumPy array without changing its data.This is essential for data preprocessing, machine learning, image processing, and scientific computing.

#### Key NumPy Functions for Reshaping

- `reshape()`: Changes the shape of an array.
- `flatten()`: creates a new 1D array (copy), Flattens a multi-dimensional array into 1D.
- `ravel()`: Similar to flatten but returns a view if possible.
- `resize()`: Changes the shape and can modify the original array.
- `transpose()`: Swaps axes (e.g., convert rows to columns).



### Summary Table

| Function                 | Description                          | Use Case Example                |
|--------------------------|--------------------------------------|---------------------------------|
| reshape()                | Change array shape                   | Prep data for ML model          |
| flatten()                | Array to 1D (copy)                   | Save as CSV                     |
| ravel()                  | Array to 1D (view if possible)       | Quick flatten, less memory      |
| resize()                 | Change shape, modifies original      | Add padding rows/cols           |
| transpose()/T            | Swap axes                            | Row/column operations           |

#### Key Takeaways

- Always ensure the total number of elements remains the same when reshaping.
- Reshaping is essential for preparing image, audio, and sensor data for machine learning models.
- Flattening is commonly used to convert 2D images or matrices into 1D feature vectors.
- Transposing is useful for switching between row-major and column-major formats, such as in time series or tabular data.
- Automatic dimension inference (`-1`) simplifies reshaping when working with large, unknown datasets.
- Resizing can help when you need to pad or truncate data to fit model input requirements.
- Understanding views vs. copies (e.g., `ravel()` vs. `flatten()`) can optimize memory usage in large-scale data processing.
- Reshaping multi-dimensional arrays is common in medical imaging, video processing, and scientific simulations.
- Proper reshaping enables seamless integration with libraries like scikit-learn, TensorFlow, and PyTorch.

In [1]:
import numpy as np

arr = np.arange(12)       # [0, 1, ..., 11]
b = arr.reshape((3, 4))   # 3 rows, 4 columns
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
# Reshape From 1-D to 3-D
reshaped = arr.reshape(4, 3) 
print('Original array shape:', arr.shape)
print('Reshaped to [4,3]:')
print(reshaped)
print('\nArray dimensions:', reshaped.ndim)
print('Array shape:', reshaped.shape)

# It will modify orignal arr
reshaped[1, 1] = 555

print("Array: ", arr)

Original array shape: (12,)
Reshaped to [4,3]:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array dimensions: 2
Array shape: (4, 3)
Array:  [  1   2   3   4 555   6   7   8   9  10  11  12]


In [4]:
# Flattening the arrays, Using -1 for Automatic Dimension Calculation
flatten = reshaped.reshape(-1)
flatten

array([  1,   2,   3,   4, 555,   6,   7,   8,   9,  10,  11,  12])

In [5]:
a = np.arange(24)
b = a.reshape((2, -1, 4))  # NumPy calculates the missing dimension
print("shape: ", b.shape)  # (2, 3, 4)
print("N-dim: ", b.ndim)   # 3
b

shape:  (2, 3, 4)
N-dim:  3


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
# Transpose: swap rows and columns
a = np.array([[1, 2], [3, 4], [5, 6]])
print("a:\n", a)
print("-" * 40)

print('Transpose:')
a = a.T
print(a)

a:
 [[1 2]
 [3 4]
 [5 6]]
----------------------------------------
Transpose:
[[1 3 5]
 [2 4 6]]


In [7]:
hours_in_month_array = np.arange(30*24) # 720 items (Each day in Month)
hours_per_day = hours_in_month_array.reshape(30, 24)  # 30 days, 24 hours each

print("The 1D array representing total hours in the month has shape: \n", hours_in_month_array.shape)
print("The reshaped 2D array (30 days, 24 hours per day) has shape: \n", hours_per_day.shape)

The 1D array representing total hours in the month has shape: 
 (720,)
The reshaped 2D array (30 days, 24 hours per day) has shape: 
 (30, 24)


##### Resizing Arrays

`resize()` can change the size, padding with zeros or repeating if necessary.

In [8]:
# Resizing Arrays
a = np.array([1, 2, 3, 4])
a.resize((2, 3))  # Now shape is (2, 3)
print('resize((2, 3)): \n', a)

b = np.array([1, 2, 3, 4])
b.resize(3,5) # 3 Rows
print('resize((3, 5)): \n', b)

c = b.reshape(-1)
print("Flat:\n",c)

resize((2, 3)): 
 [[1 2 3]
 [4 0 0]]
resize((3, 5)): 
 [[1 2 3 4 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Flat:
 [1 2 3 4 0 0 0 0 0 0 0 0 0 0 0]
